// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: servicet.proto

#include "servicet.pb.h"
#include "servicet.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>

class MockDeviceStateStub : public DeviceState::StubInterface {
 public:
  MOCK_METHOD3(UpdateWorkArea, ::grpc::Status(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::WorkAreaStateReply* response));
  MOCK_METHOD3(AsyncUpdateWorkAreaRaw, ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>*(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncUpdateWorkAreaRaw, ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>*(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq));
};

