// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: servicet.proto
#ifndef GRPC_servicet_2eproto__INCLUDED
#define GRPC_servicet_2eproto__INCLUDED

#include "servicet.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// 调度作为服务端
class DeviceState final {
 public:
  static constexpr char const* service_full_name() {
    return "DeviceState";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::WorkAreaStateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>> AsyncUpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>>(AsyncUpdateWorkAreaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>> PrepareAsyncUpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>>(PrepareAsyncUpdateWorkAreaRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>* AsyncUpdateWorkAreaRaw(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WorkAreaStateReply>* PrepareAsyncUpdateWorkAreaRaw(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::WorkAreaStateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>> AsyncUpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>>(AsyncUpdateWorkAreaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>> PrepareAsyncUpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>>(PrepareAsyncUpdateWorkAreaRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response, std::function<void(::grpc::Status)>) override;
      void UpdateWorkArea(::grpc::ClientContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>* AsyncUpdateWorkAreaRaw(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WorkAreaStateReply>* PrepareAsyncUpdateWorkAreaRaw(::grpc::ClientContext* context, const ::WorkAreaReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateWorkArea_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UpdateWorkArea(::grpc::ServerContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateWorkArea(::grpc::ServerContext* context, ::WorkAreaReq* request, ::grpc::ServerAsyncResponseWriter< ::WorkAreaStateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateWorkArea<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::WorkAreaReq, ::WorkAreaStateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WorkAreaReq* request, ::WorkAreaStateReply* response) { return this->UpdateWorkArea(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateWorkArea(
        ::grpc::MessageAllocator< ::WorkAreaReq, ::WorkAreaStateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WorkAreaReq, ::WorkAreaStateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateWorkArea(
      ::grpc::CallbackServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UpdateWorkArea<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateWorkArea(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateWorkArea(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateWorkArea(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateWorkArea : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateWorkArea() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WorkAreaReq, ::WorkAreaStateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WorkAreaReq, ::WorkAreaStateReply>* streamer) {
                       return this->StreamedUpdateWorkArea(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateWorkArea() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateWorkArea(::grpc::ServerContext* /*context*/, const ::WorkAreaReq* /*request*/, ::WorkAreaStateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateWorkArea(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WorkAreaReq,::WorkAreaStateReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateWorkArea<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateWorkArea<Service > StreamedService;
};


#endif  // GRPC_servicet_2eproto__INCLUDED
